### PR TITLE
post-processing: add link to repository issues

### PR DESCRIPTION
**Pull request by DavidKorczynski**
When fuzz-introspector is used on OSS-Fuzz it may be non-obvious where
to file suggestions and issues. To guide the user to the
fuzz-introspector repository include a short message in the navigation
bar directing where to file this.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@AdamKorcz @Navidem WDYT?

**Comment by AdamKorcz** [comment]
The URL will not be a link now. Should we wrap it in an `<a>` tag?

**Comment by DavidKorczynski** [comment]
> Good idea! The URL will not be a link now. Should we wrap it in an `<a>` tag?

I think we should!

**Review by Navidem — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
