### PR TITLE
analysis plugins: add metadata plugin

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Display the data used for constructing the fuzzing report.

Includes links to .covreport, .data, .data.yaml

Ref: https://github.com/ossf/fuzz-introspector/issues/485

Build logs will come at a later stage.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Screenshot from 2022-08-25 17-05-39

**Review by AdamKorcz — APPROVED** [review]

**Comment by evverx** [comment]
It seems to be working. Thanks! Given that build logs are tracked in https://github.com/ossf/fuzz-introspector/issues/176 I think it's safe to say that https://github.com/ossf/fuzz-introspector/issues/485 is fixed. I'll go ahead and close it. I still think that it would be great if FI could show covered functions that aren't included in call graphs but it's a separate issue.

**Comment by DavidKorczynski** [comment]
> I still think that it would be great if FI could show covered functions that aren't included in call graphs but it's a separate issue.

I think that would be real nice. Will fix this up

**Comment by evverx** [comment]
> The goal is to use the runtime information to extend the callgraph whenever we observe something like this, because it's a fact whatever is executed is in essence within reach of the fuzzer

I agree they should probably be combined one way or another but I think in some cases it would mask build issues that should probably be fixed. For example some parts of call trees get lost because fuzz targets are linked against dependencies that have been compiled differently or they can be linked against shared libraries. Coverage data can be used to somewhat restore call trees there but fuzz targets like that still need fixing.

**Pull request merged**
