### PR TITLE
[Java Integration] : Dig up necessary information from the static analysis

### PR DESCRIPTION
**Pull request by arthurscchan**
Dig up different information from the static analysis and call graph generation for fuzz introspector's further processing.
Also apply test on larger java project.

Referring to Steps 2 - 3 in Issue #536 

Signed-off-by: Arthur Chan <arthur.chan@adalogics.com>

### CODE REVIEW

**Comment by arthurscchan** [comment]
FunctionTest.java
```
package Function;

public class FunctionTest {
	public void function1() {
		System.out.println("F1");
	}

	public static void function2() {
		System.out.println("F2");
	}

	public void functionPublicDead() {
		System.out.println("PuD");
	}

	private void functionPrivateDead() {
		System.out.println("PrD");
	}

}
```
TestFuzzer.java
```
package Fuzz;

import Function.FunctionTest;
import com.code_intelligence.jazzer.api.FuzzedDataProvider;

public class TestFuzzer {
	public static void fuzzerTestOneInput(FuzzedDataProvider data) {
		int choice = data.consumeInt(0,1);

		if (choice == 0) {
			FunctionTest ft = new FunctionTest();
			ft.function1();
		} else {
			FunctionTest.function2();
		}
	}
}
```

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
Could we output the data in a Yaml format similar to https://github.com/ossf/fuzz-introspector/blob/main/doc/LanguageImplementation.md#example-of-program-wide-data-file ?

**Comment by arthurscchan** [comment]
### **Sample result, I am still digging into soot to find a way to get those "null" informations.**
```
filename: "Fuzz.TestFuzzer"
functionConfig:
  listName: "All functions"
  functionElements:
  - functionName: "<init>"
    functionSourceFile: "Fuzz.TestFuzzer"
    linkageType: null
    functionLinenumber: 21
    functionDepth: null
    returnType: "void"
    argCount: 0
    argTypes: []
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 0
    functionReached: []
    functionUses: 0
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
  - functionName: "fuzzerTestOneInput"
    functionSourceFile: "Fuzz.TestFuzzer"
    linkageType: null
    functionLinenumber: 23
    functionDepth: null
    returnType: "void"
    argCount: 1
    argTypes:
    - "com.code_intelligence.jazzer.api.FuzzedDataProvider"
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 5
    functionReached:
    - "<java.lang.Object: void <clinit>()>"
    - "<Function.FunctionTest: void function1()>"
    - "<Function.FunctionTest: void <init>()>"
    - "<java.lang.Object: void <clinit>()>"
    - "<Function.FunctionTest: void function2()>"
    functionUses: 0
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
  - functionName: "main"
    functionSourceFile: "Fuzz.TestFuzzer"
    linkageType: null
    functionLinenumber: 34
    functionDepth: null
    returnType: "void"
    argCount: 1
    argTypes:
    - "java.lang.String[]"
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 0
    functionReached: []
    functionUses: 0
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null


---
filename: "Function.FunctionTest"
functionConfig:
  listName: "All functions"
  functionElements:
  - functionName: "<init>"
    functionSourceFile: "Function.FunctionTest"
    linkageType: null
    functionLinenumber: 19
    functionDepth: null
    returnType: "void"
    argCount: 0
    argTypes: []
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 1
    functionReached:
    - "<java.lang.Object: void <init>()>"
    functionUses: 1
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
  - functionName: "function1"
    functionSourceFile: "Function.FunctionTest"
    linkageType: null
    functionLinenumber: 21
    functionDepth: null
    returnType: "void"
    argCount: 0
    argTypes: []
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 3
    functionReached:
    - "<java.lang.System: void <clinit>()>"
    - "<java.io.PrintStream: void println(java.lang.String)>"
    - "<java.lang.Object: void <clinit>()>"
    functionUses: 1
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
  - functionName: "function2"
    functionSourceFile: "Function.FunctionTest"
    linkageType: null
    functionLinenumber: 25
    functionDepth: null
    returnType: "void"
    argCount: 0
    argTypes: []
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 0
    functionReached: []
    functionUses: 1
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
  - functionName: "functionPublicDead"
    functionSourceFile: "Function.FunctionTest"
    linkageType: null
    functionLinenumber: 29
    functionDepth: null
    returnType: "void"
    argCount: 0
    argTypes: []
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 0
    functionReached: []
    functionUses: 0
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
  - functionName: "functionPrivateDead"
    functionSourceFile: "Function.FunctionTest"
    linkageType: null
    functionLinenumber: 33
    functionDepth: null
    returnType: "void"
    argCount: 0
    argTypes: []
    constantsTouched: []
    argNames: []
    iCount: null
    edgeCount: 0
    functionReached: []
    functionUses: 0
    branchProfiles: null
    bbcount: null
    cyclomaticComplexity: null
```

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
Please add licenses where applicable.

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
