### PR TITLE
workflows: run only on pull, not push

### PR DESCRIPTION
**Pull request by DavidKorczynski**
The workflow of this repository is to do everything through pull requests.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by Navidem** [comment]
Was this the reason for red CI recently?!

**Comment by DavidKorczynski** [comment]
> Was this the reason for red CI recently?!

Yeah -- I think what happened was the scorecard app would only run on push rather than pull, so we did not see it before merging it in and thought all is well and sound. Am looking at these things now in order to strengthen the CI

**Comment by Navidem** [comment]
Great, thanks!

**Pull request merged**
