### PR TITLE
Add SECURITY-INSIGHTS.yml

### PR DESCRIPTION
**Pull request by luigigubello**
**Draft PR, don't merge.** See Issue #624. This PR adds [SECURITY-INSIGHTS.yml](https://github.com/ossf/security-insights-spec) in the repo. Review and approval from maintainers are required before merging.

Missing keys:

- [security-contacts](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L74), [security-policy](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L84), and [email-contact](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L83): these keys are required by the schema, and we cannot merge the PR until this project doesn't have a security policy (e.g. `SECURITY.md`), and a security contact. If fuzz-introspector is part of OpenSSF, we should have an organization security policy, I will write a message in OpenSSF Slack. Is it okay for you?
- [security-testing](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L42): this section is missing because I prefer help filling it out. In the folder workflows I can see some security CI flows: `scorecards-analysis.yml`, `codeql-analysis.yml`, `dependabot.yml`, maybe others. Can you help me to identify tests that improve the security posture?
- [bug-bounty-available](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L85): is there a bug bounty program for this project? Maybe this should be a question for OpenSSF org.
- [dependencies-lists](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L98): I have identified only `requirements.txt`, but maybe there are more dependencies files in the repo (e.g. `go.sum`, `Dockerfile`, `package.json`, other `requirements.txt`). If so, may you point out the missing ones?
- [sbom](https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/examples/security-insights-sample.yml#L100): I was not able to find any SBOM files. Do you have SBOM for this project?

Thanks in advance for your help 🙌 

Signed-off-by: Luigi Gubello <luigi.gubello@gmail.com>

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
> * Can you help me to identify tests that improve the security posture?

[cflite_pr.yml](https://github.com/ossf/fuzz-introspector/blob/main/.github/workflows/cflite_pr.yml) is a fuzzing-centric workflow and I would add it to the list of security-relevant CI jobs

**Comment by DavidKorczynski** [comment]
> * Do you have SBOM for this project?

No, not at this stage

**Comment by DavidKorczynski** [comment]
> * is there a bug bounty program for this project? Maybe this should be a question for OpenSSF org.

No bug bounty, and agreed this is something for OpenSSF, am happy to join the discussion

**Comment by luigigubello** [comment]
@DavidKorczynski I am working on it. I will tag you in the message 🙌 thank you!:)

**Pull request closed without merging**
