### PR TITLE
Bump to more recent OSS-Fuzz

### PR DESCRIPTION
**Pull request by MarcoFalke**
This is needed to include fixes from Nov 15 (example: https://github.com/google/oss-fuzz/commit/e23200e1e4bdd9247d3ef5797e9ff9c472054894)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The patch applies, but I haven't tested this

**Comment by DavidKorczynski** [comment]
Thanks! I will test this shortly and merge in if it works

**Comment by MarcoFalke** [comment]
Hmm, I am running into another issue in bitcoin-core down the line now. Do you have any objections bumping to current master of OSS-Fuzz?

**Comment by MarcoFalke** [comment]
If yes, I'd probably have to force to `llvmorg-12-init-17251-g6de48655`?

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Thanks @MarcoFalke ! 

I tested this on one application (htslib) and verified it worked there. I had to push this as well but besides that all went smooth: https://github.com/ossf/fuzz-introspector/commit/e6e276b5db2711b4c6277b6a7144adde19bdcfcc 

Heads-up if you run this on Bitcoin as I think you may run into this issue: https://github.com/ossf/fuzz-introspector/issues/3

**Pull request merged**
