### PR TITLE
fuzz-engine-input: demangle func names

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Ref:
https://github.com/ossf/fuzz-introspector/pull/252#issuecomment-1122651603

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Example outputs:
htslib:
```
{
    "fuzzers": {
        "hts_open_fuzzer": {
            "focus-functions": [
                "view_sam",
                "bcf_hdr_read",
                "bgzf_hopen",
                "possibly_expand_bam_data",
                "bcf_hdr_parse",
                "sam_parse1",
                "bgzf_read_block",
                "sam_hdr_destroy",
                "sam_read1"
            ]
        }
    }
}
```

unrar:
```
{
    "fuzzers": {
        "unrar_fuzzer": {
            "focus-functions": [
                "CommandData::ProcessSwitch(wchar_t const*)",
                "WideToChar(wchar_t const*, char*, unsigned long)",
                "toupperw(int)",
                "File::DirectRead(void*, unsigned long)",
                "StringList::AddString(wchar_t const*)",
                "wcsicomp(wchar_t const*, wchar_t const*)",
                "FindFile::FastFind(wchar_t const*, FindData*, bool)",
                "wcsupper(wchar_t*)",
                "File::Close()",
                "StringList::AddString(wchar_t const*)"
            ]
        }
    }
}
```

jsoncpp:
```
{
    "fuzzers": {
        "jsoncpp_fuzzer": {
            "focus-functions": [
                "Json::Value::CZString::~CZString()",
                "Json::CharReaderBuilder::newCharReader() const",
                "LLVMFuzzerTestOneInput"
            ]
        },
        "jsoncpp_proto_fuzzer": {
            "focus-functions": [
                "void google::protobuf::internal::InternalMetadata::MergeFrom<google::protobuf::UnknownFieldSet>(google::protobuf::internal::InternalMetadata const&)",
                "void google::protobuf::internal::InternalMetadata::Delete<google::protobuf::UnknownFieldSet>()",
                "google::protobuf::internal::InternalMetadata::InternalMetadata(google::protobuf::Arena*, bool)",
                "json_proto::JsonParseAPI::JsonParseAPI(google::protobuf::Arena*, bool)",
                "google::protobuf::internal::InternalMetadata::arena() const",
                "json_proto::JsonProtoConverter::AppendNumber(json_proto::NumberValue const&)",
                "google::protobuf::MessageLite::MessageLite()",
                "google::protobuf::MessageLite::~MessageLite()",
                "google::protobuf::internal::InternalMetadata::arena() const"
            ]
        }
    }
}
```

**Comment by DavidKorczynski** [comment]
hmm -- there should probably be some more filtering on the focus functions looking at the above functions (e.g. LLVMFuzzerTestOneInput). Although it's fair that LLVMFuzzerTestOneInput is one of the areas where a blocker will be placed considering the output is from running 15 seconds each library.

**Comment by DavidKorczynski** [comment]
The `jsoncpp` example after running the fuzzers for 5 minutes each:
```
{
    "fuzzers": {
        "jsoncpp_proto_fuzzer": {
            "focus-functions": [
                "void google::protobuf::internal::InternalMetadata::MergeFrom<google::protobuf::UnknownFieldSet>(google::protobuf::internal::InternalMetadata const&)",
                "void google::protobuf::internal::InternalMetadata::Delete<google::protobuf::UnknownFieldSet>()",
                "google::protobuf::internal::InternalMetadata::InternalMetadata(google::protobuf::Arena*, bool)",
                "json_proto::JsonParseAPI::JsonParseAPI(google::protobuf::Arena*, bool)",
                "google::protobuf::internal::InternalMetadata::arena() const",
                "json_proto::JsonProtoConverter::AppendNumber(json_proto::NumberValue const&)",
                "google::protobuf::MessageLite::MessageLite()",
                "google::protobuf::MessageLite::~MessageLite()",
                "google::protobuf::internal::InternalMetadata::arena() const"
            ]
        },
        "jsoncpp_fuzzer": {
            "focus-functions": [
                "Json::Value::CZString::~CZString()",
                "Json::CharReaderBuilder::newCharReader() const"
            ]
        }
    }
}
```
I'm happy to leave this as is for now.

**Comment by Navidem** [comment]
> 
> I'm happy to leave this as is for now.

This looks great! Thanks!

**Review by Navidem — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Thanks! Could we do squash merging moving forward (similar to OSS-Fuzz)? -- I think it makes the commit history a little bit nicer and makes it possible to have commits e.g. "nit" in the PR without those nits getting merged in as individual commits

**Comment by Navidem** [comment]
> Thanks! Could we do squash merging moving forward (similar to OSS-Fuzz)?

Sure, will keep it in mind!

**Comment by oliverchang** [comment]
+1 to squash. I just disabled the other PR merging methods so squash is now the only option :)

**Pull request merged**
