### PR TITLE
html_report: add report generation timestamp

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Ref: https://github.com/ossf/fuzz-introspector/issues/468

### CODE REVIEW

**Review by Navidem — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Screenshot from 2022-08-24 19-06-21

**Comment by Navidem** [comment]
> Screenshot from 2022-08-24 19-06-21

Nice!

**Comment by evverx** [comment]
Thanks! To judge from
Screenshot 2022-08-25 at 14 40 40
it seems to show dates only. I tend to generate a few reports and view them at the same time so I'd probably add `%H:%M:%S` there to make it easier to tell them apart. I can send a PR if it makes sense.

**Comment by DavidKorczynski** [comment]
> I tend to generate a few reports and view them at the same time so I'd probably add `%H:%M:%S` there to make it easier to tell them apart. I can send a PR if it makes sense.

If you find it useful to have the precise timestamp then I'd be happy to have it and accept the PR!

I was a bit on the fence about this the main thing was once I reviewed the code I thought we should add a timezone if displaying the precise timestamp. The timezone required an extract package and I wasn't entirely sure what the hours+sec would add from a user perspective as for local runs I use the counter on the `corpus-` dirs to identify "when it was run". That said, I don't have any strong opinion on this and am happy to accept precise timestamp without timezone too!

**Comment by evverx** [comment]
> I reviewed the code I thought we should add a timezone if displaying the precise timestamp

That's a good point. I'd just probably go with UTC but as far as I can tell it wouldn't be consistent with other dates on OSS-Fuzz. Let's put this idea on hold :-)

> I use the counter on the corpus- dirs to identify "when it was run"

I run FI in containers and forward ports to a VM where they are forwarded to a real machine :-) so in my case it's easier to memorize ports.

**Pull request merged**
